version: '3.8'

services:
    mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: your_root_password # CHANGE THIS
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
